name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "=> Navigating to project directory"
            cd /var/www/doruk.wtf
            source ~/.profile
            source ~/.bashrc
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            echo "=> Git version and configuration:"
            git --version
            git config --get remote.origin.url
            echo "=> Fetching latest changes..."
            GIT_SSH_COMMAND="ssh -v" git fetch origin
            echo "=> Pulling latest changes..."
            git pull origin main
            echo "=> Verifying yarn installation"
            which yarn || { echo "Yarn not found. Installing..."; npm install -g yarn; }
            echo "=> Installing dependencies..."
            yarn install || { echo "Yarn install failed"; exit 1; }
            echo "=> Building project..."
            yarn build || { echo "Build failed"; exit 1; }
            echo "=> Deployment completed successfully"
