name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            echo "=> Navigating to project directory"
            cd /var/www/doruk.wtf

            echo "=> Pulling latest changes..."
            git pull

            echo "=> Installing dependencies..."
            yarn || { echo "Yarn install failed"; exit 1; }

            echo "=> Building project..."
            yarn build || { echo "Build failed"; exit 1; }

            echo "=> Project builded successfully"
